version: "3.8"
# Overrides for local development only, binds local directory to the node container and starts nodemon, these are automatically applied
services:
  node:
    working_dir: /usr/src/app
    entrypoint: sh -c "npm install --include=dev && npm run serve"
    environment: 
      - CHOKIDAR_USEPOLLING=true
    volumes:
      - ./server:/usr/src/app
  vue:
    build: 
      context: ./client/
      target: 'develop-stage'
    volumes: 
      - ./client:/app
    ports:
      - "8080:8080"
    entrypoint: sh -c "npm install && npm run serve"
    environment: 
      - CHOKIDAR_USEPOLLING=true