POST https://cloudboys-webapp2.azurewebsites.net/
content-type: application/json

{
    "username": "fromthebackend"
}

###

DELETE http://localhost:9000/container
content-type: application/json

{
    "username": "faint-deer"
}

###

POST http://localhost:9000/container/stop
content-type: application/json

{
    "username": "warm-woodpecker"
}

###

POST http://localhost:9000/container/start
content-type: application/json
{
    "username": "stormy-sparrow"
}